services:
  db:
#    image: pgvector/pgvector:pg16
    build:
      context: ./postgres-pgvector
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    container_name: somnio-pg
    networks:
      - somnio-net
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
#    image: pgvector/pgvector:pg16
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    networks:
      - somnio-net
    environment:
      - APP_PORT=3000
      - NODE_ENV=${NODE_ENV}
      - STAGE=${STAGE}
      - SEEDING=${SEEDING}
      - OPEN_IA_APIKEY=${OPEN_IA_APIKEY}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    container_name: somnio-api
    ports:
      - "3000:3000"
volumes:
  db:
    driver: local
networks:
  somnio-net:
    name: somnio-net
